"""Human-in-the-loop: :class:`HITLItem` schemas, on-disk artifacts, and resolver."""

from __future__ import annotations

from edvise.genai.mapping.identity_agent.hitl.hook_generation import (
    apply_term_hook_preview_names_from_item_id,
    apply_term_hook_spec_names_from_item_id,
    assemble_hook_spec_drafts_as_module_text,
    build_hook_generation_system_prompt,
    build_hook_generation_user_message,
    default_hook_module_relpath,
    extract_config_snippet_for_hook_item,
    generate_hook_spec,
    generate_hook_specs_for_hook_items,
    hook_slug_from_item_id,
    normalized_column_names_from_raw_headers,
    ensure_hook_spec_file,
    materialize_hook_spec_to_file,
    materialize_hook_specs_to_file,
    merge_hook_specs,
    parse_hook_spec,
    resolve_hook_module_path,
    write_identity_hook_preview_json,
)
from edvise.genai.mapping.identity_agent.hitl.artifacts import (
    build_grain_config_for_resolver,
    build_term_config_for_resolver,
    load_grain_contracts_from_resolver_config,
    load_term_contracts_from_resolver_config,
    unique_hitl_items_by_item_id,
    write_identity_grain_artifacts,
    write_identity_term_artifacts,
)
from edvise.genai.mapping.identity_agent.hitl.resolver import (
    HITLValidationError,
    HookValidationError,
    apply_hook_spec,
    check_gate,
    count_term_hook_required_streams,
    get_hook_items,
    resolve_items,
    validate_hook,
    validate_term_hook_hitl_covers_hook_required,
    validate_term_year_semantics_resolved,
)
from edvise.genai.mapping.identity_agent.hitl.schemas import (
    GrainAmbiguityHITLContext,
    GrainCandidateKeyEntry,
    GrainResolution,
    HITLDomain,
    HITLItem,
    HITLOption,
    HITLTarget,
    InstitutionHITLItems,
    ReentryDepth,
    TermResolution,
)
from edvise.genai.mapping.shared.hitl import HITLBlockingError

__all__ = [
    "build_hook_generation_system_prompt",
    "build_hook_generation_user_message",
    "default_hook_module_relpath",
    "extract_config_snippet_for_hook_item",
    "generate_hook_spec",
    "generate_hook_specs_for_hook_items",
    "normalized_column_names_from_raw_headers",
    "ensure_hook_spec_file",
    "GrainAmbiguityHITLContext",
    "GrainCandidateKeyEntry",
    "GrainResolution",
    "HITLBlockingError",
    "HITLDomain",
    "HITLItem",
    "HITLOption",
    "HITLTarget",
    "HITLValidationError",
    "HookValidationError",
    "InstitutionHITLItems",
    "parse_hook_spec",
    "ReentryDepth",
    "TermResolution",
    "apply_hook_spec",
    "apply_term_hook_preview_names_from_item_id",
    "apply_term_hook_spec_names_from_item_id",
    "assemble_hook_spec_drafts_as_module_text",
    "hook_slug_from_item_id",
    "build_grain_config_for_resolver",
    "build_term_config_for_resolver",
    "load_grain_contracts_from_resolver_config",
    "load_term_contracts_from_resolver_config",
    "materialize_hook_spec_to_file",
    "materialize_hook_specs_to_file",
    "merge_hook_specs",
    "resolve_hook_module_path",
    "check_gate",
    "count_term_hook_required_streams",
    "unique_hitl_items_by_item_id",
    "get_hook_items",
    "resolve_items",
    "validate_hook",
    "validate_term_hook_hitl_covers_hook_required",
    "validate_term_year_semantics_resolved",
    "write_identity_grain_artifacts",
    "write_identity_hook_preview_json",
    "write_identity_term_artifacts",
]
