"""
Pydantic models for Schema Mapping Agent (2a) HITL review.

HITLItems are generated by the refinement+HITL LLM call for fields that:
  - Failed deterministic validation AND could not be auto-corrected, OR
  - Have confidence < HITL_CONFIDENCE_THRESHOLD

Each SMAHITLItem targets a single FieldMappingRecord. Options are complete
FieldMappingRecord alternatives — reviewer picks one, resolver swaps it in place.
The last option is always option_id='direct_edit' with field_mapping=None, allowing
the reviewer to manually author a correction in the Streamlit UI.

Resolver contract:
    resolve_sma_items(hitl_path, manifest_path, resolved_by)
        — for each resolved item, swaps manifest.mappings[target_field] with
          selected option's field_mapping (or direct_edit_field_mapping if direct edit).
        — updates review_status on the resolved record.
        — appends to run_log.json.

File layout per institution:
    institutions/<institution_id>/
        sma_hitl.json           ← written by refinement+HITL LLM call
        sma_manifest_output.json ← refined manifest, updated in place by resolver
        run_log.json            ← append-only audit trail (shared with IdentityAgent)

Scope: Schema Mapping Agent (2a) only.
2b HITL (map_values, transformation plan corrections) is future scope.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .schemas import ColumnAlias, FieldMappingManifest, FieldMappingRecord


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HITL_CONFIDENCE_THRESHOLD: float = 0.85
"""
Fields with confidence < threshold are sent to the refinement+HITL LLM call
regardless of whether deterministic validation flagged them.
Configurable — adjust based on M2 pilot results.
"""


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class SMAReentryDepth(str, Enum):
    TERMINAL = "terminal"
    # Reviewer selected a pre-generated FieldMappingRecord option.
    # Resolver swaps it directly into the manifest.

    DIRECT_EDIT = "direct_edit"
    # Reviewer bypassed options and authored a correction directly in the UI.
    # Resolver applies direct_edit_field_mapping from the HITLItem.


class SMAFailureMode(str, Enum):
    LOW_CONFIDENCE = "low_confidence"
    # Model confidence < HITL_CONFIDENCE_THRESHOLD.
    # Options: top source column candidates the model was choosing between,
    # each as a complete FieldMappingRecord with the candidate source_column set.

    COLUMN_NOT_FOUND = "column_not_found"
    # source_column or row_selection/filter column not found in schema contract.
    # Options: close-match column candidates from training.column_details,
    # each as a complete FieldMappingRecord with the corrected column set.

    JOIN_STRUCTURE = "join_structure"
    # Join keys missing, wrong, or unresolvable across base/lookup tables.
    # Includes MISSING_COLUMN_ALIAS — options may include a column_alias correction.
    # Options: valid join key combinations from schema contract,
    # each as a complete FieldMappingRecord with corrected join + optional alias.

    ROW_SELECTION = "row_selection"
    # Wrong or missing row selection strategy for this field type.
    # Options: valid RowSelectionStrategy alternatives with args pre-filled,
    # each as a complete FieldMappingRecord with corrected row_selection.

    MAP_UNMAP = "map_unmap"
    # Model mapped a field gold would mark unmappable, or vice versa.
    # Options: always exactly two — confirm mapped (with source) or mark unmapped
    # (source_column=None, source_table=None, join=None, row_selection=None).


# ---------------------------------------------------------------------------
# SMAHITLOption
# ---------------------------------------------------------------------------


class SMAHITLOption(BaseModel):
    """
    One reviewer-selectable resolution for an SMA HITL flag.

    field_mapping is a complete FieldMappingRecord for TERMINAL options —
    the reviewer is choosing between full manifest entry alternatives,
    not just a delta. This keeps the resolver trivial (swap in place)
    and gives the reviewer full context per option.

    field_mapping is None for the direct_edit option — the reviewer
    authors the correction directly in the Streamlit manifest editor.
    """

    model_config = ConfigDict(extra="forbid")

    option_id: str = Field(
        ...,
        description="Snake-case identifier, unique within the item. e.g. 'use_term_descr'.",
    )
    label: str = Field(
        ...,
        description="Short display label (~4 words). e.g. 'Use term_descr column'.",
    )
    description: str = Field(
        ...,
        description="One sentence explaining the consequence of this choice.",
    )
    reentry: SMAReentryDepth = Field(
        ...,
        description="TERMINAL for pre-generated options, DIRECT_EDIT for escape hatch.",
    )
    field_mapping: FieldMappingRecord | None = Field(
        default=None,
        description=(
            "Complete FieldMappingRecord for this option. "
            "None only for direct_edit option — reviewer authors this in the UI."
        ),
    )
    column_alias: ColumnAlias | None = Field(
        default=None,
        description=(
            "Optional ColumnAlias to add to manifest.column_aliases when this "
            "option is selected. Populated by the LLM when a JOIN_STRUCTURE fix "
            "requires bridging a column name mismatch across tables. "
            "None for most options — only needed when join keys differ by name "
            "across base and lookup tables."
        ),
    )

    @model_validator(mode="after")
    def validate_field_mapping_presence(self) -> "SMAHITLOption":
        if self.reentry == SMAReentryDepth.TERMINAL and self.field_mapping is None:
            raise ValueError(
                "TERMINAL options must provide a complete field_mapping. "
                "field_mapping is only None for the direct_edit escape hatch."
            )
        if self.reentry == SMAReentryDepth.DIRECT_EDIT and self.field_mapping is not None:
            raise ValueError(
                "direct_edit option must have field_mapping=None — "
                "reviewer authors the correction in the UI."
            )
        return self


# ---------------------------------------------------------------------------
# SMAHITLItem
# ---------------------------------------------------------------------------


class SMAHITLItem(BaseModel):
    """
    One field-level HITL flag for Schema Mapping Agent (2a).

    Generated by the refinement+HITL LLM call for each field it could not
    auto-correct. Options are complete FieldMappingRecord alternatives.
    Reviewer sets choice to select one; resolver swaps it into the manifest.

    For direct_edit: reviewer populates direct_edit_field_mapping in the
    Streamlit UI. Resolver applies it over the current manifest entry.
    """

    model_config = ConfigDict(extra="forbid")

    item_id: str = Field(
        ...,
        description=(
            "Unique identifier for this HITL item. "
            "Convention: '{institution_id}_{entity_type}_{target_field}_{failure_mode}' "
            "e.g. 'ucf_course_term_degree_join_structure'."
        ),
    )
    institution_id: str
    entity_type: Literal["cohort", "course"]
    target_field: str = Field(
        ...,
        description="FieldMappingRecord.target_field this item applies to.",
    )
    failure_mode: SMAFailureMode = Field(
        ...,
        description="The failure category that triggered this HITL item.",
    )

    hitl_question: str = Field(
        ...,
        description=(
            "Specific, actionable question naming the field, the issue, "
            "and the decision needed. e.g. 'term_degree joins on term_desc but "
            "that column does not exist in the course table — did you mean term_descr?'"
        ),
    )
    hitl_context: str | None = Field(
        default=None,
        description=(
            "Evidence the reviewer needs to make the decision — sample values, "
            "available columns, what the model attempted and why it failed. "
            "Sourced from training.column_details and ValidationError.detail."
        ),
    )
    current_field_mapping: FieldMappingRecord = Field(
        ...,
        description=(
            "The FieldMappingRecord as produced by the refinement LLM — "
            "its best attempt after trying to auto-correct. "
            "Stored on the item so the Streamlit diff view can show "
            "what changed between current and each option."
        ),
    )
    validation_errors: list[str] = Field(
        default_factory=list,
        description=(
            "ValidationError.detail strings that triggered this item. "
            "Empty if item was triggered by low confidence only. "
            "Surfaced in hitl_context for the reviewer."
        ),
    )

    options: list[SMAHITLOption] = Field(
        ...,
        description=(
            "2-5 options. Each TERMINAL option is a complete FieldMappingRecord "
            "alternative. Last option is always option_id='direct_edit' with "
            "reentry=DIRECT_EDIT and field_mapping=None."
        ),
    )
    choice: int | None = Field(
        default=None,
        description=(
            "1-indexed reviewer selection into options. "
            "None = not yet reviewed. "
            "Resolver reads options[choice - 1]."
        ),
    )
    reviewer_note: str | None = Field(
        default=None,
        description=(
            "Optional freetext from the reviewer. "
            "Required when choice selects direct_edit — "
            "should describe the intended correction."
        ),
    )
    direct_edit_field_mapping: dict | None = Field(
        default=None,
        description=(
            "Reviewer-authored FieldMappingRecord dict, populated by Streamlit "
            "when the reviewer selects the direct_edit option. "
            "Resolver validates as FieldMappingRecord and swaps into manifest. "
            "None for all TERMINAL resolutions."
        ),
    )

    # ------------------------------------------------------------------
    # Validators
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def validate_options(self) -> "SMAHITLItem":
        n = len(self.options)
        if n < 2 or n > 5:
            raise ValueError(f"SMAHITLItem must have 2-5 options, got {n}.")
        last = self.options[-1]
        if last.option_id != "direct_edit":
            raise ValueError(
                "Last option must always be option_id='direct_edit' as the escape hatch."
            )
        if last.reentry != SMAReentryDepth.DIRECT_EDIT:
            raise ValueError("direct_edit option must have reentry=DIRECT_EDIT.")
        return self

    @model_validator(mode="after")
    def choice_in_range(self) -> "SMAHITLItem":
        if self.choice is not None and not (1 <= self.choice <= len(self.options)):
            raise ValueError(
                f"choice={self.choice} out of range — "
                f"must be between 1 and {len(self.options)}."
            )
        return self

    @model_validator(mode="after")
    def direct_edit_requires_mapping(self) -> "SMAHITLItem":
        """
        If the reviewer selected direct_edit, direct_edit_field_mapping must be set.
        Validated at resolution time — not at item creation time since the reviewer
        populates this in the Streamlit UI after item is written.
        """
        if self.is_direct_edit and self.direct_edit_field_mapping is None:
            raise ValueError(
                "direct_edit option selected but direct_edit_field_mapping is not set. "
                "Populate direct_edit_field_mapping in the Streamlit UI before resolving."
            )
        return self

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    def selected_option(self) -> SMAHITLOption | None:
        """Returns the selected option, or None if not yet reviewed."""
        if self.choice is not None:
            return self.options[self.choice - 1]
        return None

    @property
    def is_direct_edit(self) -> bool:
        """True when the reviewer selected the direct_edit escape hatch."""
        opt = self.selected_option()
        return opt is not None and opt.reentry == SMAReentryDepth.DIRECT_EDIT

    @property
    def resolved_field_mapping(self) -> FieldMappingRecord | None:
        """
        Returns the FieldMappingRecord to apply to the manifest.
        None if not yet reviewed.
        Caller must validate direct_edit_field_mapping before calling on direct_edit items.
        """
        opt = self.selected_option()
        if opt is None:
            return None
        if opt.reentry == SMAReentryDepth.DIRECT_EDIT:
            if self.direct_edit_field_mapping is None:
                return None
            return FieldMappingRecord.model_validate(self.direct_edit_field_mapping)
        return opt.field_mapping

    @property
    def resolved_column_alias(self) -> ColumnAlias | None:
        """
        Returns the ColumnAlias to append to manifest.column_aliases, if any.
        None for most resolutions — only populated on JOIN_STRUCTURE fixes
        where the selected option bridges a column name mismatch.
        Not applicable for direct_edit — reviewer owns the full correction.

        Callers should use add_alias_if_missing() rather than appending directly
        to avoid duplicates when multiple fields share the same alias correction
        (e.g. term_degree and term_declared_major both needing term_desc → term_descr).
        """
        opt = self.selected_option()
        if opt is None or opt.reentry == SMAReentryDepth.DIRECT_EDIT:
            return None
        return opt.column_alias


# ---------------------------------------------------------------------------
# Alias dedup helper
# ---------------------------------------------------------------------------


def add_alias_if_missing(
    manifest: FieldMappingManifest,
    alias: ColumnAlias,
) -> bool:
    """
    Append alias to manifest.column_aliases only if no existing entry
    already covers (table, source_column).

    Multiple HITL items can resolve to the same alias correction
    (e.g. term_degree and term_declared_major both needing
    term_desc → term_descr on the course table). This prevents
    duplicate alias entries when the resolver iterates over items.

    Returns True if the alias was added, False if it already existed.
    """
    already_exists = any(
        a.table == alias.table and a.source_column == alias.source_column
        for a in manifest.column_aliases
    )
    if not already_exists:
        manifest.column_aliases.append(alias)
        return True
    return False


# ---------------------------------------------------------------------------
# InstitutionSMAHITLItems — top-level envelope
# ---------------------------------------------------------------------------


class InstitutionSMAHITLItems(BaseModel):
    """
    All SMA HITL items for one institution run.
    Written to: institutions/<institution_id>/sma_hitl.json

    Empty items list means all fields either auto-approved or refined_by_llm —
    no human review needed, gate check passes immediately.
    """

    model_config = ConfigDict(extra="forbid")

    institution_id: str
    entity_type: Literal["cohort", "course"]
    items: list[SMAHITLItem] = Field(default_factory=list)

    @model_validator(mode="after")
    def items_match_institution(self) -> "InstitutionSMAHITLItems":
        for item in self.items:
            if item.institution_id != self.institution_id:
                raise ValueError(
                    f"SMAHITLItem '{item.item_id}' institution_id "
                    f"'{item.institution_id}' does not match envelope "
                    f"institution_id '{self.institution_id}'."
                )
        return self

    @model_validator(mode="after")
    def items_match_entity_type(self) -> "InstitutionSMAHITLItems":
        for item in self.items:
            if item.entity_type != self.entity_type:
                raise ValueError(
                    f"SMAHITLItem '{item.item_id}' entity_type "
                    f"'{item.entity_type}' does not match envelope "
                    f"entity_type '{self.entity_type}'."
                )
        return self

    @property
    def pending(self) -> list[SMAHITLItem]:
        """Items not yet reviewed — choice is None."""
        return [i for i in self.items if i.choice is None]

    @property
    def pending_direct_edits(self) -> list[SMAHITLItem]:
        """
        Items where reviewer selected direct_edit but has not yet
        populated direct_edit_field_mapping. Blocks resolution.
        """
        return [
            i for i in self.items
            if i.is_direct_edit and i.direct_edit_field_mapping is None
        ]

    @property
    def gate_pending(self) -> list[SMAHITLItem]:
        """
        All items that block the pipeline gate: no choice yet, or direct_edit
        without a populated mapping. Used by :func:`check_gate_sma_hitl`.
        """
        return self.pending + self.pending_direct_edits

    @property
    def is_clear(self) -> bool:
        """True when the gate passes — every item reviewed and direct edits complete."""
        return len(self.gate_pending) == 0


# ---------------------------------------------------------------------------
# Run log integration — SMA event shape
# ---------------------------------------------------------------------------


class SMARRunEvent(BaseModel):
    """
    One resolved SMA HITL item event.
    Appended to institutions/<institution_id>/run_log.json alongside
    IdentityAgent events — same file, different agent field.
    """

    model_config = ConfigDict(extra="forbid")

    timestamp: str
    resolved_by: str | None
    agent: str = "schema_mapping_agent"
    entity_type: str                    # "cohort" or "course"
    item_id: str
    target_field: str
    failure_mode: str
    choice: int
    option_id: str
    reentry: str                        # "terminal" or "direct_edit"


__all__ = [
    "ColumnAlias",
    "HITL_CONFIDENCE_THRESHOLD",
    "InstitutionSMAHITLItems",
    "SMAFailureMode",
    "SMAHITLItem",
    "SMAHITLOption",
    "SMAReentryDepth",
    "SMARRunEvent",
    "add_alias_if_missing",
]