"""
Materialize :class:`~edvise.genai.mapping.identity_agent.grain_inference.schemas.HookSpec` as importable Python modules.

Domain-agnostic: each ``HookFunctionSpec.draft`` is written verbatim (full ``def`` blocks).
"""

from __future__ import annotations

import ast
import logging
from pathlib import Path

from edvise.genai.mapping.identity_agent.grain_inference.schemas import HookSpec
from edvise.genai.mapping.identity_agent.hitl.hook_generation.paths import (
    resolve_hook_module_path,
)
from edvise.genai.mapping.identity_agent.hitl.schemas import HITLDomain

logger = logging.getLogger(__name__)


def materialize_hook_spec_to_file(
    hook_spec: HookSpec,
    *,
    repo_root: str | Path,
    domain: HITLDomain | None = None,
) -> Path:
    """
    Write ``hook_spec.file`` under ``repo_root`` by concatenating each function ``draft`` verbatim.

    ``repo_root`` should be the school's bronze volume root (``bronze_volumes_path`` — the same
    base used for ``cleaned/`` and ``enriched_schema_contracts/``), or any directory you treat as
    the root for relative :attr:`~edvise.genai.mapping.identity_agent.grain_inference.schemas.HookSpec.file` paths.

    Validates the assembled module with :func:`ast.parse` before writing. Optionally runs pyflakes
    (warning only). Draft vs runtime **signature** checks run in
    :func:`~edvise.genai.mapping.identity_agent.hitl.resolver.validate_hook` after import.

    ``domain`` is optional; when set, it is recorded in the module header comment only.
    """
    from edvise.genai.mapping.identity_agent.hitl.resolver import HITLValidationError

    if not hook_spec.file:
        raise HITLValidationError(
            "hook_spec.file is null — run ensure_hook_spec_file / apply_hook_spec before materialize."
        )

    try:
        out_path = resolve_hook_module_path(hook_spec.file, root=repo_root)
    except ValueError as e:
        raise HITLValidationError(str(e)) from e
    repo_root = Path(repo_root).resolve()

    text = _assemble_module_text(hook_spec, domain=domain)
    _validate_module_ast(text, out_path)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"✓ Hook module written to {out_path.relative_to(repo_root)}")

    _maybe_run_pyflakes(text, out_path)

    return out_path


def _assemble_module_text(hook_spec: HookSpec, *, domain: HITLDomain | None) -> str:
    from edvise.genai.mapping.identity_agent.hitl.resolver import HITLValidationError

    parts: list[str] = [
        "# Generated by edvise.genai.mapping.identity_agent.hitl.hook_generation.materialize — edit with care.\n"
    ]
    if domain is not None:
        parts.append(f"# HITL domain: {domain.value}\n")
    parts.append("\n")

    for i, fn in enumerate(hook_spec.functions):
        if i > 0:
            parts.append("\n\n")
        if fn.draft is None or not str(fn.draft).strip():
            raise HITLValidationError(
                f"Hook function {fn.name!r} has empty draft — cannot materialize."
            )
        parts.append(fn.draft.strip())

    return "".join(parts).rstrip() + "\n"


def _validate_module_ast(text: str, out_path: Path) -> None:
    from edvise.genai.mapping.identity_agent.hitl.resolver import HITLValidationError

    try:
        ast.parse(text)
    except SyntaxError as e:
        raise HITLValidationError(
            f"Assembled hook module failed ast.parse ({out_path}): {e}"
        ) from e


def _maybe_run_pyflakes(text: str, out_path: Path) -> None:
    try:
        from pyflakes.checker import Checker
    except ImportError:
        return
    try:
        tree = ast.parse(text)
        checker = Checker(tree, str(out_path))
        if checker.messages:
            logger.warning(
                "pyflakes reported issues in %s: %s",
                out_path,
                "; ".join(str(m) for m in checker.messages),
            )
    except Exception as e:
        logger.warning("pyflakes check skipped for %s: %s", out_path, e)


__all__ = ["materialize_hook_spec_to_file"]
